version: "1.0"
info:
  model: int-scaffold
packages:
- name: DadademoProject
  gitServerName: dadademo
  gitUrl: https://github.com/thesse1/DadademoProject
  gitUsername: thesse1
  gitBranch: main
services:
- serviceName: project.dadademo.integrations:helloworld
  packages:
  - name: DadademoProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.1020
